#!/usr/bin/env php
<?php
require_once __DIR__.'/bootstrap.php';
require_once CONFIG_DIR.'dynamo.php';
require_once CONFIG_DIR.'aws_sts_key.php';

function main($argc, $argv)
{
    $tables = array('boss_damage');

    $db = Dynamo::conn();

    foreach ($tables as $v) {
        $db->call('DeleteTable', array('TableName' => $v));
    }
}

main($argc, $argv);
